# Generated by Django 4.2.9 on 2024-01-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=200)),
                ('inverted_color', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
